name: "Build project on Windows"

on: [push]

jobs:
    build:
        name: Build project
        strategy:
            matrix:
                os: [windows-latest]
                build-configs: ["Debug", "Release"]
        runs-on: ${{ matrix.os }}
        steps: 
            - name: Checkout codebase
              uses: actions/checkout@v3
            - name: Setup MSBuild
              uses: microsoft/setup-msbuild@v1.1
              with:
                msbuild-architecture: x64
            - name: Setup premake5
              uses: abel0b/setup-premake@v2.3
              with:
                version: "5.0.0-beta2"
            - name: Generate project files
              run: premake5 vs2022
            - name: Building
              working-directory: ${{  env.GITHUB_WORKSPACE  }}
              run: msbuild /m /p:Configuration=${{matrix.build-configs}} ${{  env.SOLUTION_FILE_PATH  }}
